{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "python ma\n",
    "nage.py createsuperuser\n",
    "\n",
    "You have 18 unapplied migration(s). Your project may not work properly until you apply the migrations for app(s): admin, auth, contenttypes, sessions.\n",
    "Run 'python manage.py migrate' to apply them.        \n",
    "Traceback (most recent call last):\n",
    "  File \"C:\\Users\\poppo\\Desktop\\github ai\\end to end by vivek\\repo-79-CRUD-mastery-with-Django\\venv\\Lib\\site-packages\\django\\db\\backends\\utils.py\", line 105, in _execute\n",
    "    return self.cursor.execute(sql, params)\n",
    "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
    "  File \"C:\\Users\\poppo\\Desktop\\github ai\\end to end by vivek\\repo-79-CRUD-mastery-with-Django\\venv\\Lib\\site-packages\\django\\db\\backends\\sqlite3\\base.py\", line 329, in execute\n",
    "    return super().execute(query, params)\n",
    "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
    "sqlite3.OperationalError: no such table: auth_user   \n",
    "\n",
    "The above exception was the direct cause of the following exception:\n",
    "\n",
    "Traceback (most recent call last):\n",
    "  File \"C:\\Users\\poppo\\Desktop\\github ai\\end to end by vivek\\repo-79-CRUD-mastery-with-Django\\crm\\manage.py\", line 22, in <module>\n",
    "    main()\n",
    "  File \"C:\\Users\\poppo\\Desktop\\github ai\\end to end by vivek\\repo-79-CRUD-mastery-with-Django\\crm\\manage.py\", line 18, in main\n",
    "    execute_from_command_line(sys.argv)\n",
    "  File \"C:\\Users\\poppo\\Desktop\\github ai\\end to end by vivek\\repo-79-CRUD-mastery-with-Django\\venv\\Lib\\site-packages\\django\\core\\management\\__init__.py\", line 442, in execute_from_command_line\n",
    "    utility.execute()\n",
    "  File \"C:\\Users\\poppo\\Desktop\\github ai\\end to end by vivek\\repo-79-CRUD-mastery-with-Django\\venv\\Lib\\site-packages\\django\\core\\management\\__init__.py\", line 436, in execute\n",
    "    self.fetch_command(subcommand).run_from_argv(self.argv)\n",
    "  File \"C:\\Users\\poppo\\Desktop\\github ai\\end to end by vivek\\repo-79-CRUD-mastery-with-Django\\venv\\Lib\\site-packages\\django\\core\\management\\base.py\", line 413, in run_from_argv\n",
    "    self.execute(*args, **cmd_options)\n",
    "  File \"C:\\Users\\poppo\\Desktop\\github ai\\end to end by vivek\\repo-79-CRUD-mastery-with-Django\\venv\\Lib\\site-packages\\django\\contrib\\auth\\management\\commands\\createsuperuser.py\", line 89, in execute\n",
    "    return super().execute(*args, **options)\n",
    "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
    "  File \"C:\\Users\\poppo\\Desktop\\github ai\\end to end by vivek\\repo-79-CRUD-mastery-with-Django\\venv\\Lib\\site-packages\\django\\core\\management\\base.py\", line 459, in execute\n",
    "    output = self.handle(*args, **options)\n",
    "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
    "  File \"C:\\Users\\poppo\\Desktop\\github ai\\end to end by vivek\\repo-79-CRUD-mastery-with-Django\\venv\\Lib\\site-packages\\django\\contrib\\auth\\management\\commands\\createsuperuser.py\", line 110, in handle\n",
    "    default_username = get_default_username(database=database)\n",
    "                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
    "  File \"C:\\Users\\poppo\\Desktop\\github ai\\end to end by vivek\\repo-79-CRUD-mastery-with-Django\\venv\\Lib\\site-packages\\django\\contrib\\auth\\management\\__init__.py\", line 169, in get_default_username\n",
    "    auth_app.User._default_manager.db_manager(database).get(\n",
    "  File \"C:\\Users\\poppo\\Desktop\\github ai\\end to end by vivek\\repo-79-CRUD-mastery-with-Django\\venv\\Lib\\site-packages\\django\\db\\models\\manager.py\", line 87, in manager_method\n",
    "    return getattr(self.get_queryset(), name)(*args, **kwargs)\n",
    "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
    "  File \"C:\\Users\\poppo\\Desktop\\github ai\\end to end by vivek\\repo-79-CRUD-mastery-with-Django\\venv\\Lib\\site-packages\\django\\db\\models\\query.py\", line 645, in get\n",
    "    num = len(clone)\n",
    "          ^^^^^^^^^^\n",
    "  File \"C:\\Users\\poppo\\Desktop\\github ai\\end to end by vivek\\repo-79-CRUD-mastery-with-Django\\venv\\Lib\\site-packages\\django\\db\\models\\query.py\", line 382, in __len__\n",
    "    self._fetch_all()\n",
    "  File \"C:\\Users\\poppo\\Desktop\\github ai\\end to end by vivek\\repo-79-CRUD-mastery-with-Django\\venv\\Lib\\site-packages\\django\\db\\models\\query.py\", line 1928, in _fetch_all\n",
    "    self._result_cache = list(self._iterable_class(self))\n",
    "                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
    "  File \"C:\\Users\\poppo\\Desktop\\github ai\\end to end by vivek\\repo-79-CRUD-mastery-with-Django\\venv\\Lib\\site-packages\\django\\db\\models\\query.py\", line 91, in __iter__\n",
    "    results = compiler.execute_sql(\n",
    "              ^^^^^^^^^^^^^^^^^^^^^\n",
    "  File \"C:\\Users\\poppo\\Desktop\\github ai\\end to end by vivek\\repo-79-CRUD-mastery-with-Django\\venv\\Lib\\site-packages\\django\\db\\models\\sql\\compiler.py\", line 1562, in execute_sql\n",
    "    cursor.execute(sql, params)\n",
    "  File \"C:\\Users\\poppo\\Desktop\\github ai\\end to end by vivek\\repo-79-CRUD-mastery-with-Django\\venv\\Lib\\site-packages\\django\\db\\backends\\utils.py\", line 122, in execute\n",
    "    return super().execute(sql, params)\n",
    "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
    "  File \"C:\\Users\\poppo\\Desktop\\github ai\\end to end by vivek\\repo-79-CRUD-mastery-with-Django\\venv\\Lib\\site-packages\\django\\db\\backends\\utils.py\", line 79, in execute\n",
    "    return self._execute_with_wrappers(\n",
    "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
    "  File \"C:\\Users\\poppo\\Desktop\\github ai\\end to end by vivek\\repo-79-CRUD-mastery-with-Django\\venv\\Lib\\site-packages\\django\\db\\backends\\utils.py\", line 92, in _execute_with_wrappers\n",
    "    return executor(sql, params, many, context)      \n",
    "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^      \n",
    "  File \"C:\\Users\\poppo\\Desktop\\github ai\\end to end by vivek\\repo-79-CRUD-mastery-with-Django\\venv\\Lib\\site-packages\\django\\db\\backends\\utils.py\", line 100, in _execute\n",
    "    with self.db.wrap_database_errors:\n",
    "  File \"C:\\Users\\poppo\\Desktop\\github ai\\end to end by vivek\\repo-79-CRUD-mastery-with-Django\\venv\\Lib\\site-packages\\django\\db\\utils.py\", line 91, in __exit__ \n",
    "    raise dj_exc_value.with_traceback(traceback) from exc_value\n",
    "  File \"C:\\Users\\poppo\\Desktop\\github ai\\end to end by vivek\\repo-79-CRUD-mastery-with-Django\\venv\\Lib\\site-packages\\django\\db\\backends\\utils.py\", line 105, in _execute\n",
    "    return self.cursor.execute(sql, params)\n",
    "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
    "  File \"C:\\Users\\poppo\\Desktop\\github ai\\end to end by vivek\\repo-79-CRUD-mastery-with-Django\\venv\\Lib\\site-packages\\django\\db\\backends\\sqlite3\\base.py\", line 329, in execute\n",
    "    return super().execute(query, params)\n",
    "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
    "django.db.utils.OperationalError: no such table: auth_user"
   ]
  }
 ],
 "metadata": {
  "language_info": {
   "name": "python"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
